# Generated by Django 5.2.4 on 2025-07-21 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_vote_ratio_project_vote_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='featured_img',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
    ]
