# Generated by Django 5.2.5 on 2025-08-22 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='total_obj',
            new_name='total_tasks',
        ),
    ]
