# Generated by Django 5.2.5 on 2025-08-22 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_rename_total_obj_goal_total_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='api_image',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
